### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by oguzsh** [Kadermiyanyedi/TravelAgenda#1]
Hi @Kadermiyanyedi ✌️ 

I think you should add **"requirements.txt**" in the agenda folder because if a developer wants to work on the Django side, they can't know which packages to install, that's why you should add.

Have a nice day 🌹

**Comment by Kadermiyanyedi** [comment]
Hi @oguzsh 
I added requirements.txt. Thanks for the suggestion.
Have a nice day :)
